 FROM ace-dev-only:latest

RUN mkdir /home/aceuser/bars

RUN chown aceuser:mqbrkrs /home/aceuser/bars 
COPY sample/bars_aceonly /home/aceuser/bars 
RUN cd /home/aceuser/ace-server && ls && chmod -R 777 /home/aceuser/bars
RUN cd /home/aceuser/bars && ls && . /opt/ibm/ace-11/server/bin/mqsiprofile && mqsicreatebroker NODE1 && mqsistart NODE1 && mqsicreateexecutiongroup NODE1 -e Server1 && mqsideploy NODE1 -e Server1 -a sample.bar
