 FROM ace-dev-only:latest

RUN mkdir /home/aceuser/bars

RUN chown aceuser:mqbrkrs /home/aceuser/bars && chmod -R 775 /home/aceuser/bars
ADD sample/bars_aceonly /home/aceuser/bars
RUN cd /home/aceuser/ace-server && ls
RUN cd /home/aceuser/bars && ls && . /opt/ibm/ace-11/server/bin/mqsiprofile && mqsibar -a sample.bar -c -w /home/aceuser/ace-server
